import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import siteConfig from "./site-config";

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    "get-started",
    {
      type: "category",
      label: siteConfig.phrases["%EMBEDDED_DESIGNER%"],
      collapsed: false,
      items: [
        "building",
        "flows",
        "steps",
        "passing-data-between-steps",
        "branching",
        "looping",
        "triggering",
        "testing",
        "enabling",
        "error-handling",
        "http-requests",
        "raw-request-actions",
        "custom-code",
        "runner-environment",
      ],
    },
    {
      type: "category",
      label: "Config Wizard",
      collapsed: false,
      items: [
        "config-wizard/overview",
        "config-wizard/config-pages",
        "config-wizard/config-variables",
      ],
    },
    {
      type: "category",
      label: "Connections",
      collapsed: false,
      items: ["connections/overview", "oauth2"],
    },
    {
      type: "category",
      label: "Connectors",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "connectors" }],
      link: {
        type: "generated-index",
        title: "Connectors",
      },
    },
  ],
};

export default sidebars;
